# Generated by Django 3.1.7 on 2021-03-03 19:53

import diagnosticApp.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('activated_at', models.BooleanField(default=True, verbose_name='Ativo em')),
                ('image', stdimage.models.StdImageField(upload_to=diagnosticApp.models.get_file_path, verbose_name='Imagem')),
                ('diagnostic', models.CharField(choices=[('covid', 'COVID'), ('no-deteccion', 'SEM DETECÇAO'), ('pneumonia', 'PNEUMONIA')], max_length=15, null=True, verbose_name='Diagnóstico')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
