# Generated by Django 3.1.7 on 2021-03-21 19:30

import diagnosticApp.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('activated_at', models.BooleanField(default=True, verbose_name='Ativo em')),
                ('image', stdimage.models.StdImageField(upload_to=diagnosticApp.models.get_file_path, verbose_name='Imagem')),
                ('predict_covid', models.FloatField(blank=True, null=True, verbose_name='Previsão Covid')),
                ('predict_no_findings', models.FloatField(blank=True, null=True, verbose_name='Previsão Sem Doença')),
                ('predict_pneumonia', models.FloatField(blank=True, null=True, verbose_name='Previsão Pneumonia')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
