# Generated by Django 3.1.7 on 2021-03-03 20:20

import diagnosticApp.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to=diagnosticApp.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
