# Generated by Django 3.1.7 on 2021-03-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticApp', '0003_auto_20210303_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='diagnostic',
            field=models.CharField(blank=True, choices=[('covid', 'COVID'), ('no-deteccion', 'SEM DETECÇAO'), ('pneumonia', 'PNEUMONIA')], max_length=15, null=True, verbose_name='Diagnóstico'),
        ),
    ]
